#: import Factory kivy.factory.Factory
MDScreenManager:
    id:wind_manager
    
   
   
    MDScreen:
        name:"loading"
        id:loading
        MDFloatLayout:
            md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (1.0, 0.973, 0.882, 1)
            MDLabel:
                pos_hint: {'center_x': 0.5,'center_y': 0.6}
                text: app.waiting_text
                color:(0.0, 0.302, 0.251, 1) if not app.dark_app else (1.0, 0.973, 0.882, 1)
                halign:"center"
                font_name:"arb_fnt"
                font_size:"20sp"
    MDScreen:
        name:"main"
        id:main
        MainScreen:
            id:main_s
#############################################################################
#all motoons screens are in here
#############################################################################
    TohfaScreen:
        name:"to7fa"
        id:tohfa

    DjScreen:
        name:"Dj"
        id:Dj
    IBN_BScreen:
        name:"ibn_b"
        id:ibn_b
    AL_SHATScreen:
        name:"al_shat"
        id:al_shat

    MojmelScreen:
        name:"mojmel"
        id:mojmel

#############################################################################
#all motoons explanation screens are in here
#############################################################################
    Tohfa_E_Screen:
        name:"to7fa_E"
        id:tohfa_E
     
    Dj_E_Screen:
        name:"Dj_E"
        id:Dj_E

    IBN_B_E_Screen:
        name:"ibn_b_E"
        id:ibn_b_E

    AL_SHAT_E_Screen:
        name:"al_shat_E"
        id:al_shat_E

    Mojmel_E_Screen:
        name:"mojmel_E"
        id:mojmel_E




<MainScreen>:
    orientation: 'vertical'
    BottomNavBar:
        id:nav_bar



<BottomNavBar>:
    orientation: 'vertical'

    MDBoxLayout:
        orientation: 'horizontal'
        size_hint_y:0.08
        size_hint_x:1

        MDGridLayout:
            id:options_grid
            size_hint_x: 0.8
            pos_hint: {"x":0,"center_y":0.5}
            cols:5
            Options:
                size_hint_x:1
                angle: 90
                theme_text_color:"Custom"
                text_color:  (0.0, 0.302, 0.251, 1) if not app.dark_app else (1.0, 0.973, 0.882, 1)
            MDIconButton:
                id:D_L_mode
                icon:'moon-waning-crescent' if app.dark_app else 'weather-sunny'
                theme_text_color:"Custom"
                text_color: (0.0, 0.302, 0.251, 1) if not app.dark_app else (1.0, 0.973, 0.882, 1)
                size_hint_x:1
                opacity:0
                disabled:True
                ripple_alpha:0
                pos_hint:{'center_x':0.5,'center_y':0.5}
                on_press:
                    root.Switch_mode(app.dark_app)
                        
            MDIconButton:
                id:donation
                icon:'gift'
                size_hint_x:1
                opacity:0
                ripple_alpha:0
                theme_text_color:"Custom"
                text_color: (0.0, 0.302, 0.251, 1) if not app.dark_app else (1.0, 0.973, 0.882, 1)
                disabled:True
                pos_hint:{'center_x':0.5,'center_y':0.5}
                on_press: 
                    Factory.Gift_popup().create()
                    
            MDIconButton:
                id:info
                icon:'information'
                size_hint_x:1
                opacity:0
                ripple_alpha:0
                disabled:True
                theme_text_color:"Custom"
                text_color: (0.0, 0.302, 0.251, 1) if not app.dark_app else (1.0, 0.973, 0.882, 1)
                on_press: Factory.Info_popup().open()
                pos_hint:{'center_x':0.5,'center_y':0.5}
            MDIconButton:
                id:socials
                icon:'contacts'
                size_hint_x:1
                opacity:0
                disabled:True
                ripple_alpha:0
                pos_hint:{'center_x':0.5,'center_y':0.5}
                theme_text_color:"Custom"
                text_color: (0.0, 0.302, 0.251, 1) if not app.dark_app else (1.0, 0.973, 0.882, 1)
                on_press: Factory.Socials_popup().open()


                 
 
    MDBoxLayout:
        orientation: 'vertical'

        MDBottomNavigation:
            id: nav_parent
            on_current: root.current_tab = self.current
            panel_color: (0.0, 0.302, 0.251, 1) if app.dark_app else (1.0, 0.973, 0.882, 1)

            MDBottomNavigationItem:
                id: mtn
                name: "mutoon"
                on_tab_press: root.set_current_tab("mutoon")
                icon: "book-open-page-variant" if root.current_tab == 'mutoon' else "book-open-variant"
                text: ""
                Muton_Full_Widget:

            MDBottomNavigationItem:
                id: mtn_explan
                name: "explained_mutoon"
                on_tab_press: root.set_current_tab("explained_mutoon")
                icon: "book-open-page-variant" if root.current_tab == 'explained_mutoon' else "book-open-variant"
                text: ""
                Explanation_of_Muton_Full_Widget:



<Options>:

    theme_text_color: "Custom"
    text_color: 1, 1, 1, 1
    on_release:
        root.is_pressed= not root.is_pressed
        root.Show_Options()
    


<Muton_Full_Widget>:
    
    FloatLayout:
        MDLabel:
            id: lab
            text: root.mtn_text
            font_name: 'arb_fnt'
            halign: "center"
            size_hint: 0.5, 0.5
            pos_hint: {'center_x': 0.5, 'top': 0.85}
            opacity: 1 
            disabled: True

        MDScrollView:
            size_hint: 1, 1
            pos_hint: {'center_x': 0.5, 'top': 0.95}
            Muton_btns:
                size_hint_y: None
                height: self.minimum_height

<Muton_btns>:

    cols:2
    orientation: 'lr-tb'
    CustomImageButton:
        source: "UI/Light/To7fa.png" if app.dark_app else "UI/Dark/To7fa.png"
        label_text: root.tohfa
        click:root.go_to_tohfa
    CustomImageButton:
        source: "UI/Light/EL_Djazaria.png" if app.dark_app else "UI/Dark/EL_Djazaria.png"
        label_text:root.Djazzeria
        click:root.go_to_Dj

    Widget:
        size_hint_y: None
        height: dp(40)
    Widget:
        size_hint_y: None
        height: dp(40)
    CustomImageButton:
        source: "UI/Light/ibn_b.png" if app.dark_app else "UI/Dark/ibn_b.png"
        label_text:root.ibn_b
        click:root.go_to_ibn_b

    CustomImageButton:
        source: "UI/Light/al_shatibiya.png" if app.dark_app else "UI/Dark/al_shatibiya.png"
        label_text:root.al_shatibiya
        click:root.go_to_al_shat
    # padding for rows only
    Widget:
        size_hint_y: None
        height: dp(40)
    Widget:
        size_hint_y: None
        height: dp(40)
    CustomImageButton:
        source: "UI/Light/mojmel.png" if app.dark_app else "UI/Dark/mojmel.png"
        label_text:root.mojmel
        click:root.go_to_mojmel
       






<Explanation_of_Muton_Full_Widget>:
    FloatLayout:
        MDLabel:
            text: root.mtn_text_explan
            font_name:'arb_fnt'
            halign:"center"
            size_hint: 0.5, 0.5
            opacity: 1
            pos_hint: {'center_x': 0.5,'top': 0.85}
            disabled: True
        MDScrollView:
            size_hint: 1, 1
            pos_hint: {'center_x': 0.5, 'top': 0.95}   
            Explanation_of_Muton_btns:
                size_hint_y: None
                height: self.minimum_height


<Explanation_of_Muton_btns>: 

    cols:2
    orientation: 'lr-tb'   
    CustomImageButton:
        source: "UI/Light/To7fa_E.png" if app.dark_app else "UI/Dark/To7fa_E.png"
        label_text: root.tohfa_E
        click:root.go_to_tohfa_E
    CustomImageButton:
        source: "UI/Light/EL_Djazaria_E.png" if app.dark_app else "UI/Dark/EL_Djazaria_E.png"
        label_text:root.Djazzeria_E
        click:root.go_to_Dj_E

    Widget:
        size_hint_y: None
        height: dp(40)
    Widget:
        size_hint_y: None
        height: dp(40)
    CustomImageButton:
        source: "UI/Light/ibn_b_E.png" if app.dark_app else "UI/Dark/ibn_b_E.png"
        label_text:root.ibn_b_E
        click:root.go_to_ibn_b_E

    CustomImageButton:
        source: "UI/Light/al_shatibiya_E.png" if app.dark_app else "UI/Dark/al_shatibiya_E.png"
        label_text:root.al_shatibiya_E
        click:root.go_to_al_shat_E
    # padding for rows only
    Widget:
        size_hint_y: None
        height: dp(40)
    Widget:
        size_hint_y: None
        height: dp(40)
    CustomImageButton:
        source: "UI/Light/mojmel_E.png" if app.dark_app else "UI/Dark/mojmel_E.png"
        label_text:root.mojmel_E
        click:root.go_to_mojmel_E
#Screens init for KV      
<TohfaScreen>: 
    MDNavigationLayout:
        md_bg_color:1,1,1,1
        ScreenManager:
            Screen:
                MDBoxLayout:
                    orientation: 'vertical'
                    MDFloatLayout:
                        id:top_menu
                        size_hint_y:0.09
                        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                       
                        MDLabel:
                            opacity:0
                            id:title
                            text:root.title
                            pos_hint: {'x':0.19,'center_y': 0.5}
                            color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            font_name:"arb_fnt"
                            halign: "center"
                            size_hint_y: 0.2
                            font_size: "18sp"
                        MDIconButton:
                            opacity:0
                            id:menu_btn
                            icon:"menu"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'x': 0.03,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                nav_drawer.md_bg_color=(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                                nav_drawer.set_state("open")


                        MDIconButton:
                            opacity:0
                            id:back_btn
                            icon:"arrow-left"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'right': 1,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                self.opacity=0
                                root.ids.menu_btn.opacity=0
                                root.ids.title.opacity=0
                                app.root.current="main"                                
                            
                                
                                

                    Tohfa_pages:
                        size_hint_y: 0.91 
                        size_hint_x: 1
                        
                        id:page


        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color:(0.004, 0.267, 0.129, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
            BoxLayout:
                orientation: 'vertical'

                
                ScrollView:
                    MDList:
                        size_hint_y: None
                        height: self.minimum_height
                        spacing: '10dp'
                        MDRectangleFlatButton:
                            text:root.sections[0]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(1)
                                root.ids.nav_drawer.set_state("close")
                        
                        MDRectangleFlatButton:
                            text:root.sections[1]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(1)
                                root.ids.nav_drawer.set_state("close")
                                
                           
                        MDRectangleFlatButton:
                            text:root.sections[2]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(2)
                                root.ids.nav_drawer.set_state("close")
                                
                           
                        MDRectangleFlatButton:
                            text:root.sections[3]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(2)
                                root.ids.nav_drawer.set_state("close")
                                
                        MDRectangleFlatButton:
                            text:root.sections[4]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(2)
                                root.ids.nav_drawer.set_state("close")
                                
                        MDRectangleFlatButton:
                            text:root.sections[5]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(2)
                                root.ids.nav_drawer.set_state("close")
                                
                           
                        MDRectangleFlatButton:
                            text:root.sections[6]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(3)
                                root.ids.nav_drawer.set_state("close")
                                
                        MDRectangleFlatButton:
                            text:root.sections[7]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(3)
                                root.ids.nav_drawer.set_state("close")
                                            
                        MDRectangleFlatButton:
                            text:root.sections[8]
                            font_name:"arb_fnt"
                            halign:"center"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(4)
                                root.ids.nav_drawer.set_state("close")
                                
                           
                        MDRectangleFlatButton:
                            text:root.sections[9]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(4)
                                root.ids.nav_drawer.set_state("close")
                MDLabel:
                    size_hint_y:0.05
                    text:root.copyright 
                    font_name:"arb_fnt"
                    font_size:'7sp'
                    color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                    halign:"center" 
                    vallign:"center"              
                           



<MojmelScreen>: 
    MDNavigationLayout:
        md_bg_color:1,1,1,1
        ScreenManager:
            Screen:
                MDBoxLayout:
                    orientation: 'vertical'
                    MDFloatLayout:
                        id:top_menu
                        size_hint_y:0.09
                        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                       
                        MDLabel:
                            opacity:0
                            id:title
                            text:root.title
                            pos_hint: {'x':0.1,'center_y': 0.5}
                            color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            font_name:"arb_fnt"
                            halign: "center"
                            size_hint_y: 0.2
                            font_size: "18sp"
                        MDIconButton:
                            opacity:0
                            id:menu_btn
                            icon:"menu"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'x': 0.03,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                nav_drawer.md_bg_color=(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                                nav_drawer.set_state("open")


                        MDIconButton:
                            opacity:0
                            id:back_btn
                            icon:"arrow-left"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'right': 1,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                self.opacity=0
                                root.ids.menu_btn.opacity=0
                                root.ids.title.opacity=0
                                app.root.current="main"                                
                            
                                
                                

                    Mojmel_pages:
                        size_hint_y: 0.91 
                        size_hint_x: 1
                        
                        id:page


        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color:(0.004, 0.267, 0.129, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
            BoxLayout:
                orientation: 'vertical'

                
                ScrollView:
                    MDList:
                        size_hint_y: None
                        height: self.minimum_height
                        spacing: '10dp'
                        MDRectangleFlatButton:
                            text:root.sections[0]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(1)
                                root.ids.nav_drawer.set_state("close")
                        
                        MDRectangleFlatButton:
                            text:root.sections[1]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(4)
                                root.ids.nav_drawer.set_state("close")
                        
                MDLabel:
                    size_hint_y:0.05
                    size_hint_x:1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    text:root.copyright 
                    font_name:"arb_fnt"
                    font_size:"7sp"
                    color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                    halign:"center" 
                    vallign:"center"                    
                           
                                
                           


<DjScreen>: 
    MDNavigationLayout:
        md_bg_color:1,1,1,1
        ScreenManager:
            Screen:
                MDBoxLayout:
                    orientation: 'vertical'
                    MDFloatLayout:
                        id:top_menu
                        size_hint_y:0.09
                        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                       
                        MDLabel:
                            opacity:0
                            id:title
                            text:root.title
                            pos_hint: {'x':0.1,'center_y': 0.5}
                            color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            font_name:"arb_fnt"
                            halign: "center"
                            size_hint_y: 0.2
                            font_size: "18sp"
                        MDIconButton:
                            opacity:0
                            id:menu_btn
                            icon:"menu"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'x': 0.03,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                nav_drawer.md_bg_color=(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                                nav_drawer.set_state("open")


                        MDIconButton:
                            opacity:0
                            id:back_btn
                            icon:"arrow-left"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'right': 1,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                self.opacity=0
                                root.ids.menu_btn.opacity=0
                                root.ids.title.opacity=0
                                app.root.current="main"                                
                            
                                
                                

                    Dj_pages:
                        size_hint_y: 0.91 
                        size_hint_x: 1
                        
                        id:page


        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color:(0.004, 0.267, 0.129, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
            BoxLayout:
                orientation: 'vertical'

                
                ScrollView:
                     
                    do_scroll_x: False
                    do_scroll_y: True
                    
                    MDList:

                        size_hint_y: None
                        height: self.minimum_height
                        spacing: "10dp"
                        
                        height: self.minimum_height
                        spacing: '10dp'
                        MDRectangleFlatButton:
                            text:root.sections[0]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x: 1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(1)
                                root.ids.nav_drawer.set_state("close")
                        
                        MDRectangleFlatButton:
                            text:root.sections[1]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(1)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[2]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(2)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[3]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(3)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[4]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(4)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[5]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(5)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[6]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_y:0.2
                            size_hint_x: 1

                            on_release:
                                root.ids.page.load_section(5)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[7]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x: 1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(6)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[8]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(7)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[9]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(7)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[10]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(7)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[11]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(8)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[12]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(8)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[13]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(10)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[14]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(11)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[15]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(11)
                                root.ids.nav_drawer.set_state("close")
                MDLabel:
                    size_hint_y:0.05
                    size_hint_x:1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    text:root.copyright 
                    font_name:"arb_fnt"
                    font_size:"7sp"
                    color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                    halign:"center" 
                    vallign:"center"                             
                           
                                
                           



<IBN_BScreen>: 
    MDNavigationLayout:
        md_bg_color:1,1,1,1
        ScreenManager:
            Screen:
                MDBoxLayout:
                    orientation: 'vertical'
                    MDFloatLayout:
                        id:top_menu
                        size_hint_y:0.09
                        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                       
                        MDLabel:
                            opacity:0
                            id:title
                            text:root.title
                            pos_hint: {'x':0.19,'center_y': 0.5}
                            color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            font_name:"arb_fnt"
                            halign: "center"
                            size_hint_y: 0.2
                            font_size: "18sp"
                        MDIconButton:
                            opacity:0
                            id:menu_btn
                            icon:"menu"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'x': 0.03,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                nav_drawer.md_bg_color=(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                                nav_drawer.set_state("open")


                        MDIconButton:
                            opacity:0
                            id:back_btn
                            icon:"arrow-left"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'right': 1,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                self.opacity=0
                                root.ids.menu_btn.opacity=0
                                root.ids.title.opacity=0
                                app.root.current="main"                                
                            
                                
                                

                    IBN_B_pages:
                        size_hint_y: 0.91 
                        size_hint_x: 1
                        
                        id:page


        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color:(0.004, 0.267, 0.129, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
            BoxLayout:
                orientation: 'vertical'

                
                ScrollView:
                     
                    do_scroll_x: False
                    do_scroll_y: True
                    
                    MDList:

                        size_hint_y: None
                        height: self.minimum_height
                        spacing: "10dp"
                        
                        height: self.minimum_height
                        spacing: '10dp'
                        MDRectangleFlatButton:
                            text:root.sections[0]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x: 1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(1)
                                root.ids.nav_drawer.set_state("close")
                        
                        MDRectangleFlatButton:
                            text:root.sections[1]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(6)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[2]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(7)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[3]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(9)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[4]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(10)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[5]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(11)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[6]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_y:0.2
                            size_hint_x: 1

                            on_release:
                                root.ids.page.load_section(15)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[7]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x: 1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(19)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[8]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(20)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[9]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(22)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[10]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(24)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[11]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(25)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[12]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(29)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[13]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(32)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[14]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(33)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[15]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(35)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[16]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(36)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[17]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(39)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[18]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(42)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[19]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(45)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[20]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(47)
                                root.ids.nav_drawer.set_state("close")
                      

                
                
                
                
                
                
                MDLabel:
                    size_hint_y:0.05
                    size_hint_x:1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    text:root.copyright 
                    font_name:"arb_fnt"
                    font_size:"7sp"
                    color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                    halign:"center" 
                    vallign:"center"                             
                           
                                
                           
<AL_SHATScreen>: 
    MDNavigationLayout:
        md_bg_color:1,1,1,1
        ScreenManager:
            Screen:
                MDBoxLayout:
                    orientation: 'vertical'
                    MDFloatLayout:
                        id:top_menu
                        size_hint_y:0.09
                        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                       
                        MDLabel:
                            opacity:0
                            id:title
                            text:root.title
                            pos_hint: {'x':0.19,'center_y': 0.5}
                            color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            font_name:"arb_fnt"
                            halign: "center"
                            size_hint_y: 0.2
                            font_size: "18sp"
                        MDIconButton:
                            opacity:0
                            id:menu_btn
                            icon:"menu"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'x': 0.03,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                nav_drawer.md_bg_color=(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                                nav_drawer.set_state("open")


                        MDIconButton:
                            opacity:0
                            id:back_btn
                            icon:"arrow-left"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'right': 1,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                self.opacity=0
                                root.ids.menu_btn.opacity=0
                                root.ids.title.opacity=0
                                app.root.current="main"                                
                            
                                
                                

                    AL_SHAT_pages:
                        size_hint_y: 0.91 
                        size_hint_x: 1
                        
                        id:page


        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color:(0.004, 0.267, 0.129, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
            BoxLayout:
                orientation: 'vertical'

                
                ScrollView:
                     
                    do_scroll_x: False
                    do_scroll_y: True
                    
                    MDList:

                        size_hint_y: None
                        height: self.minimum_height
                        spacing: "10dp"
                        
                        height: self.minimum_height
                        spacing: '10dp'
                        MDRectangleFlatButton:
                            text:root.sections[0]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x: 1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(1)
                                root.ids.nav_drawer.set_state("close")
                        
                        MDRectangleFlatButton:
                            text:root.sections[1]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(8)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[2]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(9)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[3]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(9)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[4]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(10)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[5]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(11)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[6]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_y:0.2
                            size_hint_x: 1

                            on_release:
                                root.ids.page.load_section(13)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[7]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x: 1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(14)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[8]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(15)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[9]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(17)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[10]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(18)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[11]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(19)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[12]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(19)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[13]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(21)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[14]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(23)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[15]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(23)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[16]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(24)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[17]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(24)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[18]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(28)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[19]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(28)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[20]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(29)
                                root.ids.nav_drawer.set_state("close")
                      
                        MDRectangleFlatButton:
                            text:root.sections[21]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(30)
                                root.ids.nav_drawer.set_state("close")
                      
                        MDRectangleFlatButton:
                            text:root.sections[22]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(31)
                                root.ids.nav_drawer.set_state("close")
                      
                        MDRectangleFlatButton:
                            text:root.sections[23]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(32)
                                root.ids.nav_drawer.set_state("close")
                      
                        MDRectangleFlatButton:
                            text:root.sections[24]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(34)
                                root.ids.nav_drawer.set_state("close")
                      
                        MDRectangleFlatButton:
                            text:root.sections[25]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(36)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[26]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(90)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[27]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(91)
                                root.ids.nav_drawer.set_state("close")
                      
                        MDRectangleFlatButton:
                            text:root.sections[28]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(93)
                                root.ids.nav_drawer.set_state("close")
                      
                
                MDLabel:
                    size_hint_y:0.05
                    size_hint_x:1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    text:root.copyright 
                    font_name:"arb_fnt"
                    font_size:"7sp"
                    color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                    halign:"center" 
                    vallign:"center"                             
                           
                                
                           




# Explanations of mutoon screens
<Tohfa_E_Screen>: 
    MDNavigationLayout:
        md_bg_color:1,1,1,1
        ScreenManager:
            Screen:
                MDBoxLayout:
                    orientation: 'vertical'
                    MDFloatLayout:
                        id:top_menu
                        size_hint_y:0.09
                        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                       
                        MDLabel:
                            opacity:0
                            id:title
                            text:root.title
                            pos_hint: {'x':0.1,'center_y': 0.5}
                            color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            font_name:"arb_fnt"
                            halign: "center"
                            size_hint_y: 0.2
                            font_size: "18sp"
                        MDIconButton:
                            opacity:0
                            id:menu_btn
                            icon:"menu"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'x': 0.03,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                nav_drawer.md_bg_color=(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                                nav_drawer.set_state("open")


                        MDIconButton:
                            opacity:0
                            id:back_btn
                            icon:"arrow-left"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'right': 1,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                self.opacity=0
                                root.ids.menu_btn.opacity=0
                                root.ids.title.opacity=0
                                app.root.current="main"                                
                            
                                
                                

                    Tohfa_E_pages:
                        size_hint_y: 0.91 
                        size_hint_x: 1
                        
                        id:page


        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color:(0.004, 0.267, 0.129, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
            BoxLayout:
                orientation: 'vertical'

                
                ScrollView:
                     
                    do_scroll_x: False
                    do_scroll_y: True
                    
                    MDList:

                        size_hint_y: None
                        height: self.minimum_height
                        spacing: "10dp"
                        
                        height: self.minimum_height
                        spacing: '10dp'
                        MDRectangleFlatButton:
                            text:root.sections[0]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x: 1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(4)
                                root.ids.nav_drawer.set_state("close")
                        
                        MDRectangleFlatButton:
                            text:root.sections[1]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(7)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[2]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(16)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[3]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(23)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[4]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(55)
                                root.ids.nav_drawer.set_state("close")
                       
                MDLabel:
                    size_hint_y:0.05
                    size_hint_x:1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    text:root.copyright 
                    font_name:"arb_fnt"
                    font_size:"7sp"
                    color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                    halign:"center" 
                    vallign:"center"                             
                           
                                
                           

<Dj_E_Screen>: 
    MDNavigationLayout:
        md_bg_color:1,1,1,1
        ScreenManager:
            Screen:
                MDBoxLayout:
                    orientation: 'vertical'
                    MDFloatLayout:
                        id:top_menu
                        size_hint_y:0.09
                        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                       
                        MDLabel:
                            opacity:0
                            id:title
                            text:root.title
                            pos_hint: {'x':0.15,'center_y': 0.5}
                            color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            font_name:"arb_fnt"
                            halign: "center"
                            size_hint_y: 0.2
                            font_size: "18sp"
                        MDIconButton:
                            opacity:0
                            id:menu_btn
                            icon:"menu"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'x': 0.03,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                nav_drawer.md_bg_color=(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                                nav_drawer.set_state("open")


                        MDIconButton:
                            opacity:0
                            id:back_btn
                            icon:"arrow-left"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'right': 1,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                self.opacity=0
                                root.ids.menu_btn.opacity=0
                                root.ids.title.opacity=0
                                app.root.current="main"                                
                            
                                
                                

                    Dj_E_pages:
                        size_hint_y: 0.91 
                        size_hint_x: 1
                        
                        id:page



        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color:(0.004, 0.267, 0.129, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
            BoxLayout:
                orientation: 'vertical'

                
                ScrollView:
                     
                    do_scroll_x: False
                    do_scroll_y: True
                    
                    MDList:

                        size_hint_y: None
                        height: self.minimum_height
                        spacing: "10dp"
                        
                        height: self.minimum_height
                        spacing: '10dp'

                        MDRectangleFlatButton:
                            text:root.sections[0]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(5)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[1]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(7)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[2]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(15)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[3]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(25)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[4]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(29)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[5]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(42)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[6]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(55)
                                root.ids.nav_drawer.set_state("close")

                        MDRectangleFlatButton:
                            text:root.sections[7]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(61)
                                root.ids.nav_drawer.set_state("close")


                        MDRectangleFlatButton:
                            text:root.sections[8]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(67)
                                root.ids.nav_drawer.set_state("close")

                        MDRectangleFlatButton:
                            text:root.sections[9]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(71)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[10]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(76)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[11]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(80)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[12]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(89)
                                root.ids.nav_drawer.set_state("close")

                        MDRectangleFlatButton:
                            text:root.sections[13]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(104)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[14]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(113)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[15]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(124)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[16]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(137)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[17]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(143)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[18]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(149)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[19]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(152)
                                root.ids.nav_drawer.set_state("close")
                        MDRectangleFlatButton:
                            text:root.sections[20]
                            font_name:"arb_fnt"
                            text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                            ripple_color: 0.2, 0.2, 0.2, 0.1
                            size_hint_x:1
                            size_hint_y:0.2
                            on_release:
                                root.ids.page.load_section(155)
                                root.ids.nav_drawer.set_state("close")



                MDLabel:
                    size_hint_y:0.05
                    size_hint_x:1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    text:root.copyright 
                    font_name:"arb_fnt"
                    font_size:"7sp"
                    color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                    halign:"center" 
                    vallign:"center"                             
                           
                                
                           



<IBN_B_E_Screen>: 
    MDNavigationLayout:
        md_bg_color:1,1,1,1
        ScreenManager:
            Screen:
                MDBoxLayout:
                    orientation: 'vertical'
                    MDFloatLayout:
                        id:top_menu
                        size_hint_y:0.09
                        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                       
                        MDLabel:
                            opacity:0
                            id:title
                            text:root.title
                            pos_hint: {'x':0.15,'center_y': 0.5}
                            color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            font_name:"arb_fnt"
                            halign: "center"
                            size_hint_y: 0.2
                            font_size: "18sp"
                        MDIconButton:
                            opacity:0
                            id:menu_btn
                            icon:"menu"
                            disabled: 'True'
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'x': 0.03,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                nav_drawer.md_bg_color=(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                                nav_drawer.set_state("open")


                        MDIconButton:
                            opacity:0
                            id:back_btn
                            icon:"arrow-left"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'right': 1,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                self.opacity=0
                                root.ids.menu_btn.opacity=0
                                root.ids.title.opacity=0
                                app.root.current="main"                                
                            
                                
                                

                    IBN_B_E_pages:
                        size_hint_y: 0.91 
                        size_hint_x: 1
                        
                        id:page
                        MDLabel:
                            text:app.not_available
                            font_name:"arb_fnt"
                            font_size:"20sp"
                            color:(0,0,0,1)
                            halign:"center"


        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color:(0.004, 0.267, 0.129, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
            BoxLayout:
                orientation: 'vertical'

                
                ScrollView:
                     
                    do_scroll_x: False
                    do_scroll_y: True
                    
                    MDList:

                        size_hint_y: None
                        height: self.minimum_height
                        spacing: "10dp"
                        
                        height: self.minimum_height
                        spacing: '10dp'
                  
                        # MDRectangleFlatButton:
                        #     text:root.sections[4]
                        #     font_name:"arb_fnt"
                        #     text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                        #     line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                        #     ripple_color: 0.2, 0.2, 0.2, 0.1
                        #     size_hint_x:1
                        #     size_hint_y:0.2
                        #     on_release:
                        #         root.ids.page.load_section(55)
                        #         root.ids.nav_drawer.set_state("close")
                       
                MDLabel:
                    size_hint_y:0.05
                    size_hint_x:1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    text:root.copyright 
                    font_name:"arb_fnt"
                    font_size:"7sp"
                    color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                    halign:"center" 
                    vallign:"center"                             
                           
                                
                           



<AL_SHAT_E_Screen>: 
    MDNavigationLayout:
        md_bg_color:1,1,1,1
        ScreenManager:
            Screen:
                MDBoxLayout:
                    orientation: 'vertical'
                    MDFloatLayout:
                        id:top_menu
                        size_hint_y:0.09
                        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                       
                        MDLabel:
                            opacity:0
                            id:title
                            text:root.title
                            pos_hint: {'x':0.15,'center_y': 0.5}
                            color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            font_name:"arb_fnt"
                            halign: "center"
                            size_hint_y: 0.2
                            font_size: "18sp"
                        MDIconButton:
                            opacity:0
                            id:menu_btn
                            icon:"menu"
                            disabled: 'True'
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'x': 0.03,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                nav_drawer.md_bg_color=(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                                nav_drawer.set_state("open")


                        MDIconButton:
                            opacity:0
                            id:back_btn
                            icon:"arrow-left"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'right': 1,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                self.opacity=0
                                root.ids.menu_btn.opacity=0
                                root.ids.title.opacity=0
                                app.root.current="main"                                
                            
                                
                                

                    AL_SHAT_E_pages:
                        size_hint_y: 0.91 
                        size_hint_x: 1
                        
                        id:page
                        MDLabel:
                            text:app.not_available
                            font_name:"arb_fnt"
                            font_size:"20sp"
                            color:(0,0,0,1)
                            halign:"center"


        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color:(0.004, 0.267, 0.129, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
            BoxLayout:
                orientation: 'vertical'

                
                ScrollView:
                     
                    do_scroll_x: False
                    do_scroll_y: True
                    
                    MDList:

                        size_hint_y: None
                        height: self.minimum_height
                        spacing: "10dp"
                        
                        height: self.minimum_height
                        spacing: '10dp'
                       
                        # MDRectangleFlatButton:
                        #     text:root.sections[4]
                        #     font_name:"arb_fnt"
                        #     text_color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                        #     line_color: (0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                        #     ripple_color: 0.2, 0.2, 0.2, 0.1
                        #     size_hint_x:1
                        #     size_hint_y:0.2
                        #     on_release:
                        #         root.ids.page.load_section(55)
                        #         root.ids.nav_drawer.set_state("close")
                       
                MDLabel:
                    size_hint_y:0.05
                    size_hint_x:1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    text:root.copyright 
                    font_name:"arb_fnt"
                    font_size:"7sp"
                    color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                    halign:"center" 
                    vallign:"center"                             
                           
                                
                           











<Mojmel_E_Screen>: 
    MDNavigationLayout:
        md_bg_color:1,1,1,1
        ScreenManager:
            Screen:
                MDBoxLayout:
                    orientation: 'vertical'
                    MDFloatLayout:
                        id:top_menu
                        size_hint_y:0.09
                        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                       
                        MDLabel:
                            opacity:0
                            id:title
                            text:root.title
                            pos_hint: {'x':0.15,'center_y': 0.5}
                            color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            font_name:"arb_fnt"
                            halign: "center"
                            size_hint_y: 0.2
                            font_size: "18sp"
                        MDIconButton:
                            opacity:0
                            id:menu_btn
                            icon:"menu"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'x': 0.03,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                nav_drawer.md_bg_color=(0.0, 0.302, 0.251, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
                                nav_drawer.set_state("open")


                        MDIconButton:
                            opacity:0
                            id:back_btn
                            icon:"arrow-left"
                            theme_text_color:"Custom"
                            text_color:(0.0, 0.302, 0.251, 1) if  not app.dark_app else (1.0, 0.973, 0.882, 1)
                            pos_hint: {'right': 1,'center_y': 0.5} 
                            ripple_alpha:0 
                            on_press:
                                self.opacity=0
                                root.ids.menu_btn.opacity=0
                                root.ids.title.opacity=0
                                app.root.current="main"                                
                            
                                
                                

                    Mojmel_E_pages:
                        size_hint_y: 0.91 
                        size_hint_x: 1
                        
                        id:page



        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color:(0.004, 0.267, 0.129, 1) if app.dark_app else (0.941, 0.918, 0.839, 1)
            BoxLayout:
                orientation: 'vertical'

                
                ScrollView:
                     
                    do_scroll_x: False
                    do_scroll_y: True
                    
                    MDList:
                        id:fehras
                        size_hint_y: None
                        height: self.minimum_height
                        spacing: "10dp"

                       

                       
                MDLabel:
                    size_hint_y:0.05
                    size_hint_x:1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    text:root.copyright 
                    font_name:"arb_fnt"
                    font_size:"7sp"
                    color:(0.9,0.9,0.9,1) if app.dark_app else (0.1,0.1,0.1,1)
                    halign:"center" 
                    vallign:"center"                             
                           
                                
                           



#custom widgets

<Info_popup>:
    size_hint: 0.8, 0.8
    background_color: (0.0, 0.302, 0.251, 1) if app.dark_app else (1.0, 0.973, 0.882, 1)
    auto_dismiss: True
    pos_hint: {'top': 0.9}
    MDCard:
        orientation: "vertical"
        radius: [15,]
        elevation: 4
        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (1.0, 0.973, 0.882, 1)
        MDBoxLayout:
            padding:"20dp"
            orientation: "vertical"
            MDCarousel:
                id:swiper
                size_hint:1,0.8   
                direction:'right'
                MDBoxLayout:
                    MDLabel:
                        text: root.info_txt
                        halign: "center"
                        font_name:"fonts/NotoKufiArabic-ExtraBold.ttf"
                        font_size:'15sp'
                        theme_text_color: "Custom"
                        text_color: (1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                MDBoxLayout:
                    Image:
                        source:"Images/1_d.png" if app.dark_app else "Images/1_l.png"  
                        keep_ratio:True,
                        size_hint:(1, 1)
                        allow_stretch:False
                        pos_hint:{'center_x': 0.5,'center_y': 0.5}
                MDBoxLayout:
                    Image:
                        source:"Images/2_d.png" if app.dark_app else "Images/2_l.png"  
                        keep_ratio:True,
                        size_hint:(1, 1)
                        allow_stretch:False
                        pos_hint:{'center_x': 0.5,'center_y': 0.5}
                MDBoxLayout:
                    Image:
                        source:"Images/3_d.png" if app.dark_app else "Images/3_l.png"  
                        keep_ratio:True,
                        size_hint:(1, 1)
                        allow_stretch:False
                        pos_hint:{'center_x': 0.5,'center_y': 0.5}
                MDBoxLayout:
                    Image:
                        source:"Images/4_d.png" if app.dark_app else "Images/4_l.png"  
                        keep_ratio:True,
                        size_hint:(1, 1)
                        allow_stretch:False
                        pos_hint:{'center_x': 0.5,'center_y': 0.5}
                MDBoxLayout:
                    Image:
                        source:"Images/5_d.png" if app.dark_app else "Images/5_l.png"  
                        keep_ratio:True,
                        size_hint:(1, 1)
                        allow_stretch:False
                        pos_hint:{'center_x': 0.5,'center_y': 0.5}
            MDRaisedButton:
                text: root.close_txt
                font_name:"fonts/NotoKufiArabic-ExtraBold.ttf"
                size_hint:0.5,0.1
                pos_hint: {'center_x': 0.5,'center_y': 0.5}
                on_release: 
                    root.dismiss()

<Socials_popup>:
    size_hint: 0.8, 0.5
    background_color: (0.0, 0.302, 0.251, 1) if app.dark_app else (1.0, 0.973, 0.882, 1)
    auto_dismiss: True
    pos_hint: {'top': 0.9}
    MDCard:
        orientation: "vertical"
        radius: [15,]
        elevation: 4
        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (1.0, 0.973, 0.882, 1)
        MDBoxLayout:
            padding:"10dp"
            orientation: "vertical"
            spacing:"20dp"
            MDLabel:
                text: root.main_txt
                halign: "center"
                vallign:"top"
                font_name:"fonts/NotoKufiArabic-ExtraBold.ttf"
                font_size:'12sp'
                theme_text_color: "Custom"
                text_color: (1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                size_hint:1,0.1
            MDBoxLayout:
                orientation:"vertical"
                spacing:"10dp"
                size_hint:1,0.8
                
                MDRectangleFlatIconButton:
                    text:"instagram"
                    icon:"instagram"
                    size_hint:0.9,0.1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    radius: [15,]
                    elevation:2
                    theme_text_color:"Custom"
                    text_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    icon_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    line_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    on_release:root.routes("https://www.instagram.com/reffaschouaib/")
                MDRectangleFlatIconButton:
                    text:"github"
                    icon:"github"
                    size_hint:0.9,0.1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    radius: [15,]
                    elevation:2
                    theme_text_color:"Custom"
                    text_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    icon_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    line_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    on_release:root.routes("https://github.com/mcy-e")
                MDRectangleFlatIconButton:
                    text:"twitter"
                    icon:"twitter"
                    size_hint:0.9,0.1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    radius: [15,]
                    elevation:2
                    theme_text_color:"Custom"
                    text_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    icon_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    line_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    on_release:root.routes("https://x.com/MRc_MCY")
                MDRectangleFlatIconButton:
                    text:"gmail"
                    icon:"gmail"
                    size_hint:0.9,0.1
                    pos_hint: {'center_x': 0.5,'center_y': 0.5}
                    radius: [15,]
                    elevation:2
                    theme_text_color:"Custom"
                    text_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    icon_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    line_color:(1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                    on_release:root.routes("mailto:reffaschouaib@gamil.com")
            MDRaisedButton:
                text: root.close_txt
                font_name:"fonts/NotoKufiArabic-ExtraBold.ttf"
                size_hint:0.5,0.2
                pos_hint: {'center_x': 0.5,'center_y': 0.5}
                on_release: root.dismiss()
<Gift_popup>:
    size_hint: 0.8, 0.3
    background_color: (0.0, 0.302, 0.251, 1) if app.dark_app else (1.0, 0.973, 0.882, 1)
    auto_dismiss: True

    MDCard:
        orientation: "vertical"
        radius: [15,]
        elevation: 4
        md_bg_color:(0.0, 0.302, 0.251, 1) if app.dark_app else (1.0, 0.973, 0.882, 1)
        MDBoxLayout:
            padding:"10dp"
            orientation: "vertical"
            spacing:"10dp"
            MDLabel:
                text: root.main_txt
                halign: "center"
                font_name:"fonts/NotoKufiArabic-ExtraBold.ttf"
                font_size:'12sp'
                theme_text_color: "Custom"
                text_color: (1, 1, 1, 1) if app.dark_app else (0.2,0.2,0.2,1)
                size_hint:1,0.8

            MDRaisedButton:
                text: root.close_txt
                font_name:"fonts/NotoKufiArabic-ExtraBold.ttf"
                size_hint:0.5,0.2
                pos_hint: {'center_x': 0.5,'center_y': 0.5}
                on_release: root.dismiss()

<CustomImageButton>:
    #*  default properties

    orientation: 'vertical'
    size_hint: 0.5, None
    height: self.width * 0.33
    spacing: "10dp"
   # the custom image 

    Image:
        id:btn_bg
        source: root.source
        size_hint_y: 0.8
        allow_stretch: True
        keep_ratio: True

    # the custom label
    MDLabel:
        text: root.label_text
        halign: "center"
        size_hint_y: 0.2
        font_size: "15sp"
        font_name:"fonts/Amiri-Regular.ttf"
        color: (1, 1, 1, 1) if app.dark_app else (0,0,0,1)




